### ISSUE TITLE
name fat images so that xen will "mount" them

### ISSUE THREAD

**Issue by mor1** [mirage/mirage#245] opened 2014-06-10 21:28 UTC
per the call today: the created fat image needs to be named with the node number and mounted as /dev/loopN so that the various xen bits will dtrt when the config file specifies them. this means bits of scripts should also be generated to allow them to be mounted as /dev/loopN 

i have a part complete implementation of most of this in my block-nodenumber-hack branch. i *think* the last (or possibly just next) remaining bit i had to was unpick the hashing that generated the `fatN.img` name so that it used the node number where appropriate. the comment in the last checkpoint commit on the above branch indicates what i was thinking at the time.

note: this is a hack to get things working. someone who understands this better than me (@djs55 springs to mind immediately) might want to suggest the "right way" to do this and thus whether it's worth completing this hack in lieu of just doing it right...

**Comment by samoht** [comment] 2015-03-17 01:13
Where this experiment went? I'm very tempted to close the issue and say it is closely related to #349 (but maybe not, as it involves `fat` and not `crunch`)

**Comment by mor1** [comment] 2015-03-17 10:22
hasn't progressed further. not clear to me this is really worth pursuing though as our FAT support isn't complete and presumably we'd be better using irmin in some way anyway...?

**Comment by avsm** [comment] 2015-03-17 10:34
FAT support is useful for USB sticks put in a cubieboard

**Comment by samoht** [comment] 2015-10-31 22:01
Seems to be a duplicate of #349

**Closed by samoht** 2015-10-31 22:01 UTC
Labels: bug
