### ISSUE TITLE
Configure Stackv41.listen_tcpv4 ~port

### ISSUE THREAD

**Issue by Chris00** [mirage/mirage#280] opened 2014-07-30 13:57 UTC
- It would be nice to be able to configure the port of the HTTP server (say for the `static_website` in `mirage-skeleton`) without having to modify the line `Stackv41.listen_tcpv4 ~port:80` in the generated `main.ml`.  An option in `config.ml` woud be nice be maybe also the possibility to set it through the `NET` variable: `NET="socket:8080"`

- IMHO it would also be better to have the default set to `` `Socket`` because it does not require root privileges (nor to set `tap0`).

**Comment by samoht** [comment] 2015-03-17 00:55
I think this has been fixed with `conduit` (/cc @avsm to double-check). Closing. Please re-open it the issue is still there.

**Closed by samoht** 2015-03-17 00:55 UTC
