### ISSUE TITLE
add a LICENSE file to the main repo

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#398] opened 2015-05-05 08:00 UTC
The copyright is present in the _oasis file and each individual header, but there should be a `LICENSE` file as well.  Noticed by @agarwal

**Comment by dsheets** [comment] 2016-01-11 17:23
I would like this, as well.

**Comment by dsheets** [comment] 2016-01-11 17:30
[scripts/nat-script.sh](https://github.com/mirage/mirage/blob/master/scripts/nat-script.sh) is GPLv2 but is a shell script and so not linked and so probably does not infect the rest of the package.

**Comment by amirmc** [comment] 2016-01-11 22:51
I’m not sure that we should be requiring LICENSE files since the code already has licence info at the top — unless the LICENSE file just says ‘see the code’, or something. Even in this repo there's an example of code that is present under different licences so one LICENSE file would be misleading.

I recall that this came up elsewhere (and I added my 2cents back then [1]).

[1] https://github.com/mirage/ocaml-conduit/issues/71#issuecomment-107898921

**Comment by djs55** [comment] 2016-01-11 23:10
I think from a user's point of view, we should make it easy as possible to
understand and comply with all the license terms of all the software in a
project (including all the dependencies). There could be a really large
number of source files compiled into a unikernel. It would be bad if a
license obligation (e.g. a GPL source code offer or an old BSD advertising
clause or a "do not evil" clause) was simply missed or a conflict between
two licenses was missed by accident.

In the case of this repo where there exists code under multiple different
licenses, a well-written LICENSE file should include all of them. I
completely agree that we want to avoid misleading information! If the
maintainers create a LICENSE file then they have an obligation to keep it
up to date, IMHO.

Does anyone know if there is a tool which could scan all source files and
create a list of all the license headers?



On Mon, Jan 11, 2016 at 10:51 PM, Amir Chaudhry <notifications@github.com>
wrote:

> I’m not sure that we should be requiring LICENSE files since the code
> already has licence info at the top — unless the LICENSE file just says
> ‘see the code’, or something. Even in this repo there's an example of code
> that is present under different licences so one LICENSE file would be
> misleading.
>
> I recall that this came up elsewhere (and I added my 2cents back then [1]).
>
> [1] mirage/ocaml-conduit#71 (comment)
> <https://github.com/mirage/ocaml-conduit/issues/71#issuecomment-107898921>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage/issues/398#issuecomment-170719348>.
>



-- 
Dave Scott

**Comment by agarwal** [comment] 2016-01-11 23:17
My additional 2 cents: I prefer a single LICENSE file, which doesn't mean there is a single license for all files. See for example the [cufp.org license](https://raw.githubusercontent.com/CUFP/cufp.org/master/src/site/license.md).

@amirmc In the comment he linked to says:

>  the separate file doesn't necessarily remove confusion as now this repo has license info in a file and in the source files

Indeed, so my solution is to *not* put the license in individual files. I find this beneficial for many reasons:

- It is difficult to look at every individual file to figure out what license(s) you are dealing with.
- It is difficult to maintain the license info. You even end up having to write code to do so, e.g. [headache](https://forge.ocamlcore.org/projects/headache/)
- I find it annoying that so many code files in the world have tens of lines at the top with information I usually don't care about, before I can finally see the actual code that I'm probably reading the file for.

**Comment by amirmc** [comment] 2016-01-11 23:20
I completely agree! User should be able to see quickly what licenses are involved in a project.

This is also made more complicated by the example in this repo. The unikernel doesn’t require the GPL shell script mentioned here but since that file does exist in the repo, it shouldn’t be forgotten if we summarise license info elsewhere.

Some kind of automated tooling would be great but I can imagine it being awkward to maintain.

**Comment by amirmc** [comment] 2016-01-11 23:44
The CUFP example is useful but it's made simpler by the fact that *all* code is ISC.  If there had been a mixture of (compatible) licenses, that section might look a lot more complicated as it would have to refer to which code-snippets were licensed differently.

Regarding Ashish's points:

> - It is difficult to look at every individual file to figure out what license(s) you are dealing with.

I agree. In my other comment, my suggestion was to mention something in the README about how most of the code is licensed (ofc this doesn't work if one is planning to build automation around it but it would suffice for most humans). If there happen to be multiple licenses in a repo, then the reader still has to go back and forth from the code files to the LICENSE file to cross-check.  

> - It is difficult to maintain the license info. You even end up having to write code to do so, e.g. headache

Yes (or copy/pasting when you create a new file).  The above scenario, with cross-checking, also requires maintenance :)

> - I find it annoying that so many code files in the world have tens of lines at the top with information I usually don't care about, before I can finally see the actual code that I'm probably reading the file for.

Perhaps, but once you've found your way to that code by whatever means, the license info is right there *in* the file (even if the file has been copied into another repo).

In any case, these issues only apply when there is code with *different* licenses. If we only ever had one license, this would be pretty trivial :)

Please note that I don't have *that* strong of an opinion as may be coming across here. :) 
I just think there are nuances and assumptions that should be stated.

**Comment by dbuenzli** [comment] 2016-01-12 00:39
> My additional 2 cents: I prefer a single LICENSE file, which doesn't mean there is a single license for all files. See for example the cufp.org license.

The problem is that more than often this single LICENSE file is misleading or gets outdated. If you are serious about IP rights you will have anyways to go through all the sources.

> It is difficult to look at every individual file to figure out what license(s) you are dealing with.

As said above this is something you will have to do anyways. 

> It is difficult to maintain the license info. You even end up having to write code to do so, e.g. headache

This is a non issue unless you change your license (which incidentally is a problem I'm soon going to have as I'm going to relicense all my sources). Copyright years don't have to updated, unless you care about your work to be protected for a few more years after your death.

> I find it annoying that so many code files in the world have tens of lines at the top with information I usually don't care about, before I can finally see the actual code that I'm probably reading the file for.

This can be alleviated by putting the license at the end (see e.g. my sources, the header is always made of exactly 5 lines, decorations included). Having all the sources with licensing included makes it easier for others to reuse them at their wish while making sure they abide to the terms and keeps lawyers away (or not). I find it annoying and problematic when source files are not properly labelled with copyrights and licensing terms.  

For these reasons (especially the first one) I find it much more productive if projects label all their sources and mention their "main" license prominently in the README and in their `opam` metadata in a machine readable format (see https://github.com/ocaml/opam/pull/2224) that `opam` lints. This will allow to create filters to make a "first pass" to select packages based on their license. Of course these will still need full inspection from a legal perspective. 

I find the benefits of a LICENSE file limited, except maybe in multi-license projects where they can provide [a birds eye view](https://github.com/dbuenzli/rpi-boot-ocaml/blob/master/libc-ocaml/LICENSE.md) of the legal crap involved.

**Comment by talex5** [comment] 2016-01-12 10:18
FWIW, at the last place I worked we used to have just a LICENSE file and a "See LICENSE file" header. However, people tended to copy files from our project into theirs, with a different license (accidentally). So I think it's worth naming the license (and copyright holder) at the top of each file. However, the text of the license doesn't need to be duplicated.

Perhaps the opam repository itself could scan each archive and extract a summary from the headers.

**Comment by avsm** [comment] 2016-01-12 10:20
> scripts/nat-script.sh is GPLv2 but is a shell script and so not linked and so probably does not infect the rest of the package.

No GPL code in this repo please. Will remove this script.

**Comment by agarwal** [comment] 2016-01-12 14:12
People copy code from or to other places is the one argument I agree with that in favor of duplicating license info in each file. However, I wonder how often this really happens. For most projects, you can't really ever drop in a file from or take a file to somewhere else and have it work.

What I have experienced myself is copying a small bit of code to somewhere else. The header won't be copied, so you have to manually think about the license and note it for that one function. In this case, there is no solution other than people being diligent.

The single LICENSE file I propose can just have a statement that says: "Here are the licenses overall, but snippets of code or whole files maybe annotated with a different license too, overriding what is stated here."

> The CUFP example is useful but it's made simpler by the fact that _all_ code is ISC.

I don't see how this is pertinent. Licenses are provided for a wide variety of assets in the repo; it so happens that all the code is one license, but the file could clearly be extended to handle different licenses for different code files.

> The problem is that more than often this single LICENSE file is misleading or gets outdated.

Yes, but that's also the case for licenses in each file. It is less so with a single file because it is easier to maintain a single file.

> If you are serious about IP rights you will have anyways to go through all the sources.

Yes, overall there's no getting around that. A single license makes maintenance by developers easier. The lawyer's job is still difficult.

> This can be alleviated by putting the license at the end

I like that.

Another way to think of the single license file is that we are factoring out the license info. It is simply an instance of DRY.

**Comment by hannesm** [comment] 2016-10-03 10:14
seems to be done in #590!?

**Comment by amirmc** [comment] 2016-10-03 11:50
Indeed. Other Mirage libs have these too. Closing this.

**Closed by amirmc** 2016-10-03 11:50 UTC
