### ISSUE TITLE
mirage-xen install error on CentOS 6.6

### ISSUE THREAD

**Issue by njbartlett** [mirage/mirage#418] opened 2015-06-17 16:43 UTC
Hi, I am trying to install Mirage with the Xen back end on a CentOS 6.6 virtual machine (running under Vagrant on Mac OS).

`opam install mirage-xen` fails due to a compilation error in `mirage-xen-minios`, as follows:

	#=== ERROR while installing mirage-xen-minios.0.7.0 ===========================#
	# opam-version         1.2.1~rc2
	# os                   linux
	# command              make build
	# path                 /home/vagrant/.opam/4.01.0/build/mirage-xen-minios.0.7.0
	# compiler             4.01.0
	# exit-code            2
	# env-file             /home/vagrant/.opam/4.01.0/build/mirage-xen-minios.0.7.0/mirage-xen-minios-16363-d2d111.env
	# stdout-file          /home/vagrant/.opam/4.01.0/build/mirage-xen-minios.0.7.0/mirage-xen-minios-16363-d2d111.out
	# stderr-file          /home/vagrant/.opam/4.01.0/build/mirage-xen-minios.0.7.0/mirage-xen-minios-16363-d2d111.err
	### stdout ###
	# [...]
	# make[1]: Entering directory `/home/vagrant/.opam/4.01.0/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os'
	# perl /home/vagrant/.opam/4.01.0/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/../../tools/include/xen-external/bsd-sys-queue-h-seddery /home/vagrant/.opam/4.01.0/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/../../tools/include/xen-external/bsd-sys-queue.h --prefix=minios  >include/list.h.new
	# if ! cmp -s include/list.h.new include/list.h; then mv -f include/list.h.new include/list.h; else rm -f include/list.h.new; fi
	# ln -sf . include/mini-os
	# ln -sf ../../../xen/include/public include/xen
	# ln -sf . arch/x86/include/mini-os
	# cp /home/vagrant/.opam/4.01.0/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/../../xen/include/xen/libfdt/fdt.h include/fdt.h
	# sed 's!xen/libfdt/!!' /home/vagrant/.opam/4.01.0/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/../../xen/include/xen/libfdt/libfdt.h > include/libfdt.h
	# gcc -DCONFIG_START_NETWORK -DCONFIG_SPARSE_BSS -DCONFIG_BLKFRONT -DCONFIG_NETFRONT -DCONFIG_KBDFRONT -DCONFIG_FBFRONT -DCONFIG_CONSFRONT -DCONFIG_XENBUS -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/4.4.7/include -fno-builtin -Wall -Werror -Wredundant-decls -Wno-format -Wno-redundant-decls -Wformat -fno-stack-protector -fgnu89-inline -Wstrict-prototypes -Wnested-externs -Wpointer-arith -Winline -O3 -fno-tree-loop-distribute-patterns -D__INSIDE_MINIOS__ -m64 -mno-red-zone -fno-reorder-blocks -fno-stack-protector -fno-asynchronous-unwind-tables -isystem /home/vagrant/.opam/4.01.0/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/../../extras/mini-os/include -D__MINIOS__ -D__XEN_INTERFACE_VERSION__=0x00030205  -isystem /home/vagrant/.opam/4.01.0/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/../../extras/mini-os/arch/x86/include -isystem /home/vagrant/.opam/4.01.0/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/../../extras/mini-os/arch/x86/include/x86_64 -c blkfront.c -o /home/vagrant/.opam/4.01.0/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/blkfront.o
	# make[1]: Leaving directory `/home/vagrant/.opam/4.01.0/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os'
	### stderr ###
	# [...]
	# ++ LIBM=openlibm-0.4.1-tal1
	# ++ LIBM_ARCHIVE=v0.4.1-tal1.tar.gz
	# ++ LIBM_URL=https://github.com/talex5/openlibm/archive/v0.4.1-tal1.tar.gz
	# + rm -rf xen-minios-v0.6
	# + tar -zxf minios-v0.6.tar.gz
	# + cd xen-minios-v0.6/extras/mini-os
	# + make debug=n
	# cc1: error: unrecognized command line option "-fno-tree-loop-distribute-patterns"
	# make[1]: *** [/home/vagrant/.opam/4.01.0/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/blkfront.o] Error 1
	# make: *** [build] Error 2

**Comment by talex5** [comment] 2015-06-18 12:59
If you can't upgrade your compiler, you could apply this patch from master to the `minios-v0.6.tar.gz` archive:

https://github.com/talex5/mini-os/commit/b49a536d02e225c410307d3bccef5f6e3c6f16a9

**Comment by njbartlett** [comment] 2015-06-18 13:48
I have no problems upgrading my compiler (assume you mean GCC?) as this is only a VM.

However I see nothing in the installation instructions for Mirage regarding a required compiler version. Can you advise? Thanks.

**Comment by talex5** [comment] 2015-06-18 13:56
The flag is needed to disable an optimisation added to later gcc versions, but isn't needed on earlier versions. However, you may have trouble with other components (e.g. crypto stuff) when using older compilers. CentOS 7 would probably work, but I haven't tried it.

(closing, as duplicate of https://github.com/mirage/mirage-xen-minios/issues/12)

**Closed by talex5** 2015-06-18 13:56 UTC
