### ISSUE TITLE
Logging doesn't work when `start` is not a function.

### ISSUE THREAD

**Issue by liautaud** [mirage/mirage#1088] opened 2020-03-20 15:48 UTC
When trying to use `Logs` in a minimal example such as [tutorial/noop-functor](https://github.com/mirage/mirage-skeleton/tree/master/tutorial/noop-functor), the logger doesn't seem to output anything to the console (which I suspect is because the reporter is not set as it should when the call to `Logs.info` is evaluated).

Here is a minimal example that should output to the console, but doesn't (with `-t macosx`):

```ocaml
(* config.ml *)
open Mirage

let main =
  foreign "Unikernel.Main" job

let () =
  register "noop" [main]
```

and either:

```ocaml
(* unikernel.ml *)
open Lwt.Infix

module Main = struct

  let start =
    Lwt.return_unit >|= fun () ->
    Logs.info (fun f -> f "foo");

end
```

or:

```ocaml
(* unikernel.ml *)
module Main = struct

  let start =
    Logs.info (fun f -> f "foo");
    Lwt.return_unit

end
```

**Comment by talex5** [comment] 2020-03-20 16:02
Well, it can't. Your `start` is a static value that is evaluated when the `Unikernel` module is initialised, before `main.ml` even runs.

**Comment by liautaud** [comment] 2020-03-20 16:21
@talex5 Makes sense, thanks. My instinct would be to turn `start` into `unit -> unit Lwt.t`, but I'm not sure how I should update `config.ml` to allow this. Any pointers?

**Comment by talex5** [comment] 2020-03-21 13:00
You could try adding `Lwt.pause () >>= fun () ->` as the first line in `start`. That should make it wait until the mainloop is ready.

**Comment by hannesm** [comment] 2020-03-21 15:00
related / duplicate of #873 -- maybe this should be documented (but I fail to find where -- maybe it is finally time to add a FAQ to our webpage)?

**Comment by hannesm** [comment] 2020-10-24 15:28
closing as duplicate of #873 where a solution is proposed (mirage should warn if start is a value instead of a function).

**Closed by hannesm** 2020-10-24 15:28 UTC
