### ISSUE TITLE
mirage-console-unix requires mirage-types < 2.2.0, which doesn't exist for ocaml 4.01.0

### ISSUE THREAD

**Issue by drbo** [mirage/mirage#345] opened 2015-01-10 05:38 UTC
When I try to install `mirage-www`, I get this error:

```
The following dependencies couldn't be met:
  - mirage-console-unix -> mirage-types < 2.2.0
Your request can't be satisfied:
  - No package matches mirage-types<2.2.0.

No solution found, exiting
```

This seems like a bug in the dependencies of `mirage-console-unix`.

**Comment by avsm** [comment] 2015-01-10 10:32
This is an older package -- @samoht, remind me again why we removed this from the repo for newer mirage?  We could replace it with a mirage-www binary that crunches up a website into a Xen stack website unikernel instead of the live website.

**Comment by avsm** [comment] 2015-01-10 10:33
For now, to get mirage-www you can:

```
opam install mirage
git clone git://github.com/mirage/mirage-www
cd mirage-www
make
```

and see the `Makefile` for options.

**Comment by samoht** [comment] 2015-02-16 17:40
>  @samoht, remind me again why we removed this from the repo for newer mirage?

can't remember why exactly ...

**Comment by samoht** [comment] 2015-03-17 00:17
I guess the `mirage-console-unix` has been superseded by `mirage-console`. @drbo why do you need this package?

**Comment by samoht** [comment] 2015-03-17 01:02
I'm closing the issue as I can't reproduce it. Please re-open if it is still an issue.

**Closed by samoht** 2015-03-17 01:02 UTC
