### ISSUE TITLE
`mirage configure` can give a misleading error message

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage#509] opened 2016-03-12 13:32 UTC
When running `mirage configure` in a directory with no `config.ml`:

```
$ mirage configure -t unix
mirage: unknown option `-t'.
Usage: mirage configure [OPTION]... 
Try `mirage configure --help' or `mirage --help' for more information.
```

**Comment by Drup** [comment] 2016-03-12 13:43
Duplicate of https://github.com/mirage/mirage/issues/461 (and others ..)

**Closed** 2016-03-12 13:44 UTC
