### ISSUE TITLE
STACKV4.UDPV4 interface: callback handling

### ISSUE THREAD

**Issue by mor1** [mirage/mirage#426] opened 2015-07-07 16:22 UTC
Specifically, it would be nice to receive the `dst_port` in the `S.listen_udpv4` callback function; and it would be nice to be able to remove `callback` functions (the latter may be possible but is not obviously documented if so).

**Comment by yomimono** [comment] 2015-07-16 16:22
What do you think of moving the `listen_udpv4` and `listen_tcpv4` functions (and associated data structures) out of Stackv4 and into UDP and TCP respectively, and making interaction with listeners abstracted through those modules (including deletion)?  

(Why? It's currently a bit annoying that there's no facility for registering listeners before calling them when dealing with UDP and TCP outside of STACK, and in the current configuration there's some potential for surprising behavior if a user calls `S.TCPV4.listen` rather than `S.listen` after registering listeners with `listen_tcpv4`.  I think if we did this, we could probably replace a lot of uses of `STACK` with `TCP` in functors like Conduit.)

**Comment by mor1** [comment] 2015-07-16 17:33
Sure-- sounds an entirely reasonable plan to me.

**Comment by hannesm** [comment] 2015-07-20 08:50
I wonder whether there should be a more generic interface:
````
module type PROTOCOL_HANDLER = sig
   type address
   type buffer
   type +'a io
   type handlers

  (** The type of a function which handles a byte vector *)
   type handle = src:address -> dst:address -> buffer -> unit io

  (** The insertion policy for conflicts *)
   type insertion_policy = [ `Overwrite | `Error | `Combine ]

  (** Allow for a catchall or a specific port (or other magic number, defined by the layer implementation). *)
   type dispatch = [ `Default | `Int of int ]

  (** [register ~if_exists handlers handle dispatch] registers the [handle] into [handlers], using
     the [if_exists] insertion policy and the [dispatch] magic.  The new [handlers], which has
     [handler] inserted is returned. *)
   val register : ?if_exists:insertion_policy -> handlers -> handle -> dispatch -> handlers

  (** [deregister handlers magic] unregisters a given [magic] from [handlers]. *)
   val deregister : handlers -> dispatch -> handlers

  (** [handle handlers frame] handles [frame] (defined by magic, source, destination, payload) *)
   val handle : handlers -> (int * address * address * buffer) -> unit io
 end
````

which can then be included by the various layers (ethernet, IP, TCP. UDP, ...).  I have an implementation thereof lying around somewhere (and some modifications to the TCP/IP stack to use this API).  An advantage for a more general API is that the code can be shared between ethernet, IP, ... (it might use a hashtable for `magic -> handler` mapping internally, or any other data structure).  Disadvantage is that atm the dispatch in ethernet is a match, which seems to be better (performance-wise) than a lookup in a hashtable (or am I misguided here?)?

**Comment by yomimono** [comment] 2015-07-21 20:35
I'd be curious to see the implementation and the expression in `tcpip`.

I don't see what happens if `insertion_policy` is `Error` and the user attempts to call `register` on a vector that's already been registered -- it looks like `register` always returns `handlers`; is it intended that an exception be thrown here, or the attempt to register just silently be discarded?

**Comment by hannesm** [comment] 2015-07-21 23:25
in that state (which is from several months ago), `` `Error` throws an exception. this is certainly not good (or finished yet, rather some initial ideas).. I'll dig out the tcpip branch tomorrow where I used the proposed protocol handler

**Comment by hannesm** [comment] 2015-07-22 15:57
I've created https://github.com/hannesm/mirage/tree/protocol_handler and https://github.com/hannesm/mirage-tcpip/tree/handler -- which at least compiles together (I disabled ipv6 support for now).. the interface proposed earlier here has changed a bit -- there is one PROTOCOL_HANDLER in mirage-types, to be used by clients, and then a functorized module (over an address) Protocol_handler which is used by ethernet, ipv4, udp:
- `connect` now registers the protocol implementation onto lower layer (no longer `input ~arp ~ipv4 ~ipv6` / `input ~icmp ~tcp ~udp`)
- `disconnect` should deregister
- `protocol dispatching is centralised (current implementation uses a hash table)
- arp is streamlined: it receives the payload of an ethernet frame, plus source and destination
- ethernet pushed mac addresses, ipv4 ipv4 addresses, udp a tuple of ipv4 address and port
- tcp is not generalized to that interface (due to flow, this is more complex and doesn't really fit (`handle` is different))

happy to hear feedback on this approach

**Comment by talex5** [comment] 2015-07-22 17:05
Hmm, interesting. A few thoughts...

The current API certainly has some problems:

- `ETHIF` is really just a splitter for forwarding ethernet frames to ARP/IPv4/IPv6 as appropriate. It should probably be a function rather than a module type. All the other functions in `ethif.ml` just forward to `NETWORK` (except `disconnect`, which mysteriously does nothing).

- `listen` in `NETWORK` means "Start an async loop handling requests", whereas `listen_tcpv4` just registers a callback. These names should probably be more different.

The problem I see with adding `register` and `deregister` to `ETHIF` is that we change a nice functional API into a stateful one (and now we have to worry about duplicate handlers and have combining policies).

I think I'd feel happier if TCP and UDP just provided the port as an argument to their (single) handler, leaving the job of deciding how to handle them to the user. That might make it easier to handle port ranges too.

It's not clear to me whether it's cleaner to have `ETHIF` or `IPV4` know the ethernet frame type for IPv4 packets. Given how rarely new types are added, I'd be tempted to leave it as it is. Though the handler arguments should probably by optional (`let input ?arpv4 ?ipv4 ?ipv6 t frame`) for future expansion.

**Comment by talex5** [comment] 2015-07-22 17:10
(but I guess we have to allow registering ports in the API for the "socket" implementation, so forget about that)

**Comment by hannesm** [comment] 2015-07-22 19:49
The problem with the current API is in my opinion that the IPv4 layer knows about ARP and Ethernet, which it shouldn't (think about PtP connections, IP over IP, ...).

I agree that a better API should be a purely functional one. In order to reach this point, the state of a layer should be completely given as input argument fror all the functions (and as result if the function is allowed to extend the state (`register`/`deregister`/`set_ip_address`/...).

I'd remove `listen_tcpv4` and `listen_udpv4`, and tell users to use `register` on the specific layer.

 > I think I'd feel happier if TCP and UDP just provided the port as an argument to their (single) handler, leaving the job of deciding how to handle them to the user. That might make it easier to handle port ranges too.

I'm not sure I understand what you mean here. `register` takes a `handle` function and a `port` argument (alternatively `default` if you're interested in all the packets (e.g. pcap capture or some strange network scenario)).

In my opinion the `input ?arpv4 ?ipv4 ?ipv6 t frame` is not flexible, which I expect from a modern TCP/IP stack. (But I'm still concerned about the performance of hashtable lookups vs manual pattern matching.)

Inspiration for this is the [click modular router](http://pdos.csail.mit.edu/papers/click:tocs00/paper.pdf) (and [my previous TCP/IP stack in Dylan](https://github.com/dylan-hackers/network-night-vision/)), and [FreeBSD netgraph](https://www.freebsd.org/cgi/man.cgi?query=netgraph&sektion=4&apropos=0&manpath=FreeBSD+10.1-RELEASE).

**Comment by samoht** [comment] 2015-07-22 22:08
I'm really keen to put as many changes as possible in the TCPI/IP signatures in the next release of mirage (2.6.*) so we break the API once.

I don't know what is the correct signature, but having pure combinators to create callbacks + a way to start to listen for packets at every layer would make sense. I'm not very fond of the `register` / `unregister` thinks, although that's maybe the only way to allow dynamic updates of the listening function(s). I can also see that the `Combine` would come handy if we want to add/remove sniffing functions in the stack dynamically (although that the `unregister` is currently now powerful enough to do that properly).

**Comment by talex5** [comment] 2015-07-23 10:47
@hannesm I meant that we could perhaps remove the register functions completely and let the application provide the mapping (with a `match` or a hashtable as desired). But actually, I see that we do it that way already (`TCP.input`).

The problem is that user applications can't rely on that, because the Unix sockets implementation requires registration. It seems to be a bit of a mess currently, because `Tcpip_stack_socket` is supposed to provide a `TCP` implementation, but looking at the code it just does this (`tcpv4_socket.ml`):

    (* FIXME: how does this work at all ?? *)
    let input _t ~listeners:_ =
      (* TODO terminate when signalled by disconnect *)
      let t, _ = Lwt.task () in
      t

Probably we should remove `TCP.input` and `UDP.input` from `mirage-types`. They're specific to the "direct" stack.

(and any combining system we come up with needs to work with Unix sockets too)

**Comment by hannesm** [comment] 2015-07-23 11:58
@talex5 I agree that `input` are only useful for `stack_direct`.

@samoht "listen for packets at every layer" - I'm not entirely sure what you mean. A top-level `listen` which receives a packet, pushes it to the output demultiplexer of the layer, and loops makes imho only sense on the lowest layer (whereas registering a handler on top of another protocol should be available on every layer).

While I'm not sure whether dynamic configuration of the stack is required, there are some examples to take into account: active FTP (separate data channel), [port knocking](https://en.wikipedia.org/wiki/Port_knocking), receive a single DHCP lease (and/or reopen listening after an interval, but no need to process all broadcast packets), sniffing of a specific layer, ...

The possibility to configure (parts) of the stack at compile-time (and maybe branch to possible dynamic listeners for packets not handled statically) sounds like a good solution (maybe `connect` should be run at compile time, and an `initialise` at runtime (which could send a gratitious ARP etc).

**Comment by samoht** [comment] 2015-07-23 13:11
What is difficult with listen is that it's something that you call on the low-level on the stack but usually you don't want to know about that low-level. I think there are two things that you want to compose when you get up the stack: the callback and the listeners (which take callbacks as parameters). Users should have a way to compose callbacks (using something similar to the policies you have defined) and the listeners should be composed by each implementations. Users should be able to update the callback used by listeners in a way which isn't clear to me yet.

I can try to come-up with a design later, but I'm not totally sure which one yet :-)

**Comment by hannesm** [comment] 2022-03-16 12:50
I'll close this issue. With recent enhancements there is now a `unlisten` to remove a callback for a specific port. And the `dst_port` can be manually passed to the callback when registering (this is what I do e.g. in the dns-resolver):

```OCaml
let cb dst_port ~src ~dst ~src_port data = ... in
UDP.listen udp ~port:23 (cb 23)
```

**Closed by hannesm** 2022-03-16 12:50 UTC
Labels: improvement
