### ISSUE TITLE
unikernels generated with mirage-seal run out of memory after a relatively small number of requests

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage#406] opened 2015-05-20 16:20 UTC
Using `mirage-seal` version 0.1.0, a generated unikernel runs out of memory and crashes after ~600 requests in series.  The same content, also served through cohttp (via mirage-http) but without tls, holds up fine through 2,000 requests (and possibly beyond; I tested only for 2,000).

All testing was done in a fresh opam switch made specifically for testing mirage-seal; there are no pins, although the `mirage-dev` repository is used.  Here's the output of `opam pin list` and `opam list`:

```
$ opam pin list
$ opam list
# Installed packages for cryptofun:
asn1-combinators          0.1.2  Combinators for expressing ASN.1 grammars in OCaml
base-bigarray              base  Bigarray library distributed with the OCaml compiler
base-bytes                 base  Bytes library distributed with the OCaml compiler
base-threads               base  Threads library distributed with the OCaml compiler
base-unix                  base  Unix library distributed with the OCaml compiler
base64                    2.0.0  Base64 encoding and decoding library
biniou                    1.0.9  Binary data format designed for speed, safety, ease of use a
camlp4                 4.02.1+2  Camlp4 is a system for writing extensible parsers for progra
cmdliner                  0.9.7  Declarative definition of command line interfaces for OCaml
cohttp                   0.17.1  HTTP library for Lwt, Async and Mirage
conduit                   0.8.3  Network connection library for TCP and SSL
conf-gmp                      1  Virtual package relying on a GMP lib system installation.
conf-pkg-config             1.0  Virtual package relying on pkg-config installation.
cppo                      1.1.2  Equivalent of the C preprocessor for OCaml programs
crunch                    1.4.0  Convert a filesystem into a static OCaml module
cstruct                   1.4.0  access C structures via a camlp4 extension
ctypes                    0.4.1  Combinators for binding to C libraries without writing any C
depext                      0.5  Query and install external dependencies of OPAM packages
dns                      0.15.0  DNS client and server implementation
dolog                       1.0  the dumb OCaml logger (lazy and optionally colorful)
easy-format               1.0.2  High-level and functional interface to the Format module of 
fieldslib             109.20.03  Syntax extension to define first class values representing r
gmp-xen                   6.0.0  The GNU Multiple Precision Arithmetic Library
io-page                   1.5.1  Allocate memory pages suitable for aligned I/O
ipaddr                    2.6.1  IP (and MAC) address representation library
lwt                       2.4.8  A cooperative threads library for OCaml
magic-mime                1.0.0  Convert file extensions to MIME types
merlin                    2.1.2  Editor helper, provides completion, typing and sources brows
mirage                    2.5.0  The Mirage library operating system
mirage-clock-unix         1.0.0  A Mirage-compatible Clock library for Unix
mirage-clock-xen          1.0.0  A Mirage-compatible Clock library for Xen
mirage-conduit            2.2.0  Virtual package for the Mirage Conduit transports
mirage-console            2.1.3  A Mirage-compatible Console library for Xen and Unix
mirage-dns                2.0.0  Virtual package for the Mirage DNS transports
mirage-entropy-xen        0.3.0  Mirage entropy device
mirage-http               2.2.0  Mirage HTTP client and server driver
mirage-net-unix           2.2.0  Ethernet network driver for Mirage, using tuntap
mirage-net-xen            1.4.1  Ethernet network device driver for Mirage/Xen
mirage-profile              0.4  Collect profiling information
mirage-seal               0.1.0  HTTPs sealing.
mirage-types              2.3.0  Module type definitions for Mirage-compatible applications
mirage-types-lwt          2.3.0  Lwt module type definitions for Mirage-compatible applicatio
mirage-unix               2.3.1  Mirage OS library for Unix compilation
mirage-xen                2.3.1  MirageOS library for Xen
mirage-xen-minios         0.7.0  Xen MiniOS guest operating system library
mirage-xen-ocaml          2.3.1  MirageOS headers for the OCaml runtime
mirage-xen-posix          2.3.1  MirageOS library for posix headers
nocrypto                  0.4.0  Small functional-style crypto library.
ocaml-src                4.02.1  Compiler sources
ocamlfind                 1.5.5  A library manager for OCaml
ocp-build           1.99.9-beta  Project manager for OCaml
ocp-indent                  1.5  A simple tool to indent OCaml programs
ocplib-endian               0.8  Optimised functions to read and write int16/32/64 from strin
ounit                     2.0.0  Unit testing framework loosely based on HUnit. It is similar
ppx_tools                0.99.2  Tools for authors of ppx rewriters and other syntactic tools
re                        1.4.0  RE is a regular expression library for OCaml
sexplib               112.24.01  Library for serializing OCaml values to and from S-expressio
shared-memory-ring        1.1.1  Shared memory rings for RPC and bytestream communications.
stringext                 1.3.1  Extra string functions for OCaml
tcpip                     2.4.3  Userlevel TCP/IP stack
tls                       0.5.0  Transport Layer Security (TLS) in OCaml
tuntap                    1.0.0  TUN/TAP bindings
type_conv             112.01.01  Library for building type-driven syntax extensions
uri                       1.9.0  RFC3986 URI/URL parsing library
vchan                     2.0.2  Xen Vchan implementation
x509                      0.3.1  X.509 certificate (RFC5280) library
xen-evtchn                1.0.6  Xen event channel bindings.
xen-gnt                   2.2.0  Xen grant table bindings
xenstore                  1.2.5  Xenstore protocol clients and server
xenstore_transport        0.9.4  Low-level libraries for connecting to a xenstore service on 
yojson                    1.2.1  Yojson is an optimized parsing and printing library for the 
zarith                      1.3  Implements arithmetic and logical operations over arbitrary-
```

**Comment by yomimono** [comment] 2015-05-20 17:03
If the `dispatch.ml` generated in `/tmp/mirage-seal` is edited to serve a static string that looks convincingly like an HTTP response and the unikernel rebuilt, we can serve at least 2,000 requests in series over TLS without running out of memory.

**Comment by samoht** [comment] 2015-05-20 17:43
TLS is exercising the Channel code quite a bilt (as it usually splits the HTTP query/response into chunks) so we might be hitting bugs in cohttp or tpcip ... does the bug is reproducible with sockets?

**Comment by yomimono** [comment] 2015-05-20 18:02
It looks like a binary generated for the same content with `mirage-seal --sockets` is fairly constant on memory usage, at least over the first few thousand requests.

On 20 May 2015 18:43:52 BST, Thomas Gazagnaire <notifications@github.com> wrote:
>TLS is exercising the Channel code quite a bilt (as it usually splits
>the HTTP query/response into chunks) so we might be hitting bugs in
>cohttp or tpcip ... does the bug is reproducible with sockets?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mirage/mirage/issues/406#issuecomment-103971606

-- 
Composed on a touchscreen keyboard; please forgive typos and brevity.

**Comment by samoht** [comment] 2015-05-21 22:15
I'm able to reproduce the issue:
```
[91] serving //192.168.33.190/.
Cannot handle page request order 8!
RX exn Out of memory
Cannot handle page request order 8!
Cannot handle page request order 8!
Fatal error: exception Out_of_memory
Raised by primitive operation at file "bigarray.ml", line 105, characters 4-39
Called from file "lib/cstruct.ml", line 90, characters 25-56
Called from file "src/hash.ml", line 48, characters 14-42
Called from file "src/uncommon.ml", line 8, characters 27-30
Called from file "src/fortuna.ml", line 92, characters 16-29
Called from file "src/fortuna.ml", line 95, characters 6-15
Called from file "src/fortuna.ml", line 57, characters 62-66
Called from file "lib/engine.ml", line 137, characters 25-65
Called from file "lib/engine.ml", line 279, characters 25-50
Called from file "lib/engine.ml", line 468, characters 4-48
Called from file "lib/engine.ml", line 494, characters 11-31
Called from file "channel/channel.ml", line 212, characters 4-24
Called from file "lib/response.ml", line 72, characters 4-119
Called from file "lib/response.ml", line 90, characters 4-23
Called from file "src/core/lwt_stream.ml", line 893, characters 10-13
Called from file "src/core/lwt.ml", line 652, characters 66-69
Called from file "bigarray.ml", line 105, characters 4-39
Called from file "lib/cstruct.ml", line 90, characters 25-56
Called from file "lib/ipv4.ml", line 108, characters 25-62
Called from file "tcp/wire.ml", line 44, characters 28-76
Called from file "tcp/pcb.ml", line 90, characters 6-79
Called from file "tcp/pcb.ml", line 130, characters 8-57
Called from file "src/core/lwt.ml", line 652, characters 66-69
Called from file "bigarray.ml", line 105, characters 4-39
Called from file "lib/cstruct.ml", line 90, characters 25-56
Called from file "src/fortuna.ml", line 116, characters 6-39
Called from file "list.ml", line 73, characters 12-15
Called from file "src/core/lwt_sequence.ml", line 149, characters 31-47
Called from file "lib/main.ml", line 66, characters 10-62
Called from file "main.ml", line 125, characters 2-77
Mirage exiting with status 2
Do_exit called!
base is 0x41ff20 caller is 0x218637
base is 0x22 Page fault
```

Seems that the number of channels in the pcb is ever growing, I'm investigating why...

**Comment by hannesm** [comment] 2015-05-21 22:49
does this also happen with tun/tap interface on unix? or only as a true unikernel on xen?

**Comment by samoht** [comment] 2015-05-21 23:19
Anything fancy with the closing of TCP connections when using TLS?

```
PCB: 0 channels / 0 listens / 0 connects
{ Closed }  - Passive_open ->  { Listen }
{ Listen }  - Send_synack 452914056 ->  { Syn_rcvd 452914056 }
{ Syn_rcvd 452914056 }  - Recv_ack 452914057 ->  { Established }
{ Established }  - Recv_ack 452914057 ->  { Established }
{ Established }  - Recv_ack 452915427 ->  { Established }
{ Established }  - Recv_ack 452915427 ->  { Established }
[192.168.33.10:52671] TLS ok
{ Established }  - Recv_ack 452915518 ->  { Established }
[1] serving //192.168.33.175/.
{ Established }  - Recv_ack 452915826 ->  { Established }
{ Established }  - Recv_ack 452915826 ->  { Established }
{ Established }  - Recv_ack 452915826 ->  { Established }
PCB.TX.close
{ Established }  - Send_fin 452915895 ->  { Fin_wait_1 452915895 }
[1] closing.
{ Fin_wait_1 452915895 }  - Recv_fin ->  { Closing 452915895 }
ARP: timeout 192.168.33.10
[... a very long time ... ]
[... curl -k -l https://192.168.33.175 has already exited for a very long time ... ]
[... ]
```

**Comment by samoht** [comment] 2015-05-22 00:02
ok so the pcb entries are not cleaned up properly from the `channels` hash-table when the server initiate the closing. I'm not sure to understand why ...

**Comment by samoht** [comment] 2015-05-22 00:13
I won't be able to do more until next Tue. would be nice if someone could try to debug that a bit more tomorrow!

**Comment by hannesm** [comment] 2015-05-23 14:52
do you have the branches somewhere on github which provide the output in a previous comment?
tls_mirage closes by first sending out a teardown message and then calling close on the underlying flow... maybe the write already fails and close is never called? (but then, your trace indicates that TX.close gets called) https://github.com/mirleft/ocaml-tls/blob/master/mirage/tls_mirage.ml#L145

**Comment by samoht** [comment] 2015-05-26 14:27
The branch is there: https://github.com/mirage/mirage-tcpip/pull/142

Doing a `curl -l -k https://<ip>` gives the following trace:

```
TCP.PCB: process-syn [0 channels / 0 listens / 0 connects]
TCP.PCB: new-server-connection [0 channels / 0 listens / 0 connects]
{ Closed }  - Passive_open ->  { Listen }
{ Listen }  - Send_synack 452906345 ->  { Syn_rcvd 452906345 }
ARP: transmitting probe -> 192.168.33.10
ARP: updating 192.168.33.10 -> 08:00:27:3f:95:6e
TCP.PCB: process-ack [0 channels / 1 listens / 0 connects]
{ Syn_rcvd 452906345 }  - Recv_ack 452906346 ->  { Established }
{ Established }  - Recv_ack 452906346 ->  { Established }
{ Established }  - Recv_ack 452907716 ->  { Established }
{ Established }  - Recv_ack 452907716 ->  { Established }
[192.168.33.10:50612] TLS ok
{ Established }  - Recv_ack 452907807 ->  { Established }
[1] serving //192.168.33.157/.
{ Established }  - Recv_ack 452908115 ->  { Established }
{ Established }  - Recv_ack 452908115 ->  { Established }
{ Established }  - Recv_ack 452908115 ->  { Established }
TCP.PCB: TX.close
{ Established }  - Send_fin 452908184 ->  { Fin_wait_1 452908184 }
[1] closing.
{ Fin_wait_1 452908184 }  - Recv_fin ->  { Closing 452908184 }
ARP: timeout 192.168.33.10
```

It seems that the timer for removing the entry is never set-up properly in the state machine. @balrajsingh or @hannesm do you have any idea? 

I'm trying to compare the code in https://github.com/mirage/mirage-tcpip/blob/master/tcp/state.ml#L114 with http://www.tcpipguide.com/free/t_TCPOperationalOverviewandtheTCPFiniteStateMachineF-2.htm there are various small difference -- in our case it seems that we have a simultaneous close but we seem to lose the last ack from the client so we never transition from `Closing` to `Time_wait` and we never trigger the clean-up timeout.

**Comment by hannesm** [comment] 2015-05-26 14:34
Thanks! I can reproduce on Unix using tun/tap (limiting process memory to 32MB it faults after 32 requests)

**Comment by hannesm** [comment] 2015-05-26 14:55
well, actually using your debug branch, I can see
````
TCP.PCB: removing pcb from tables: [1 channels / 0 listens / 0 connects]
TCP.PCB: removed from channels!!
STATE: finwait2timer: Closed
````
output after the timeouts..

**Comment by hannesm** [comment] 2015-05-26 17:04
some of the connections result in keeping in `closing` state... a pcap of such a session is available at http://www.cl.cam.ac.uk/~hm519/seal-stuff.pcap

**Comment by samoht** [comment] 2015-05-26 17:23
@hannesm my VM is till running and I have no new output on the console (so the connection is still half open). Making a new connection show that the the `channel` hash-table has still one entry.

**Comment by hannesm** [comment] 2015-05-26 17:30
yes, same for me. the pcap I posted is the capture on tap0 regarding that stale connection (using https://github.com/hannesm/mirage-tcpip/commit/0f6ceb69a3058f8778a07019ee9b1386eaf8f4c8 to display the concrete connections which are in the channels table, then some pcap filtering)

**Comment by hannesm** [comment] 2015-05-26 18:29
so, what happens here? in the pcap I linked to above our side sends a FIN+ACK (I still cannot figure why ACK is set). This frame (number 15) is not acknowledged by the other side (also not retransmitted, why?).
Instead, the other side sends a FIN+ACK folowed by RST. These are acknowledged, but the RST seems to be not handled...

**Comment by samoht** [comment] 2015-05-26 18:43
It is still not totally clear to me why this happens only with HTTP over TLS. Maybe the TLS clients are doing weird (or at least untested for our stack) things? Also, I'm not sure at all that's the main leak ...

**Comment by hannesm** [comment] 2015-05-26 18:51
not sure about 2, but 1 is most likely true: in mirage-www the server never calls `Flow.close` itself. in `mirage-seal`, `TLS.close` (which calls `TCP.close`) is called on successful HTTP transmission, thus we traverse the TCP/IP state machine differently (visiting the initiator close sequence (fin-wait1, fin-wait2, closing, time-wait)), and interplay with partial close or data loss rst frames seems to be broken..

**Comment by hannesm** [comment] 2015-05-26 19:00
@samoht can you reproduce the leak with https://github.com/hannesm/mirage-seal/tree/no-close ?

**Comment by samoht** [comment] 2015-05-26 23:05
Seem to be similar ...

```
TCP.PCB: process-syn [198 channels / 0 listens / 0 connects]
TCP.PCB: new-server-connection [198 channels / 0 listens / 0 connects]
{ Closed }  - Passive_open ->  { Listen }
{ Listen }  - Send_synack 452898747 ->  { Syn_rcvd 452898747 }
Cannot handle page request order 1!
memalign(4096, %zu) failed.
Cannot handle page request order 0!
out of memoryMirage exiting with status 2
Do_exit called!
base is 0x41fc50 caller is 0x20b52f
base is 0xc00020 caller is 0x5d4198
base is 0x5d4230 caller is 0xb00
base is 0x3aa610 caller is 0x746978452e7365
base is 0x7669736176726550 GPF rip: 233b07, error_code=0
RIP: e030:[<0000000000233b07>]
RSP: e02b:000000000041fc10  EFLAGS: 00010002
RAX: 000000000000001b RBX: 7669736176726550 RCX: 0000000000033448
RDX: 0000000000033448 RSI: 000000000041fa60 RDI: 0000000000000004
RBP: 000000000041fc50 R08: 0000000000000447 R09: 0000000000000020
R10: 000000000000001b R11: 0000000000000000 R12: 0000000000000002
R13: 00000000005d8cd8 R14: 7ffffffffffefe7f R15: 00000000005d4228
base is 0x41fc50 caller is 0x20b52f
base is 0xc00020 caller is 0x5d4198
base is 0x5d4230 caller is 0xb00
base is 0x3aa610 caller is 0x746978452e7365
base is 0x7669736176726550 GPF rip: 233ef7, error_code=0
RIP: e030:[<0000000000233ef7>]
RSP: e02b:000000000041fb38  EFLAGS: 00010016
RAX: 000000000000001b RBX: 7669736176726550 RCX: 00000000000336b9
RDX: 00000000000336b9 RSI: 000000000041f988 RDI: 0000000000000004
RBP: 000000000041fb68 R08: 00000000000006b8 R09: 0000000000000020
R10: 000000000000001b R11: 0000000000000000 R12: 0000000000000002
R13: 00000000005d8cd8 R14: 7ffffffffffefe7f R15: 00000000005d4228
base is 0x41fb68 caller is 0x7ffffffffffefe7f
base is 0x5d4228 caller is 0x3aa610
base is 0x700 Page fault at linear address 708, rip 233ef7, regs 000000000041f9a8, sp 41fa58, our_sp 000000000041f968, code 0
```

**Comment by hannesm** [comment] 2015-05-27 10:02
I gathered some statistics about the following scenarios (branch names in braces, available at https://github.com/hannesm/mirage-seal):
- cohttp and tls (master)
- no cohttp, but server static string (no-cohttp)
- no tls, but use cohttp (no-tls)
- no tls, no cohttp (nothing)

I force full major collections in these branches. Using native sockets, I get after 200 (linear) requests the following memory usage (starting with 9000kB):
- tls+cohttp (master): 12956kB
- tls (no-cohttp): 12940kB
- cohttp (no-tls): 10648kB
- nothing (nothing): 9860kB

using mirage-tcpip:
- tls+cohttp (master): 17180kB
- tls (no-cohttp): 13860kB
- cohttp (no-tls): 15000kB (after retransmission messages up to 24000kB)
- nothing (nothing): 14000kB (after retransmission messages up to 16000kB)

for my untrained eye it looks that either I'm doing something wrong, or all participating libraries are leaking a bit...

**Comment by hannesm** [comment] 2015-05-27 10:34
certainly gathering memory usage from `top` (as done above) is not optimal.. should use OCaml's GC stats

**Comment by hannesm** [comment] 2015-05-27 12:47
I updated the last comment to use `Gc.stat ()` and `live_words` from there, and reran the measurements..

**Comment by samoht** [comment] 2015-05-28 18:12
I've tried to generate nice graphs with memprof:

http://memprof.typerex.org/users/36a218e5fd31b8799a68ecea2eb14d82/2015-05-28_19-39-46_39423d31ec3d875d11466dc43535d7ef_12991/index.html

we spent some time with @hannesm and @sevenEng to try to understand what happen without too much success (only that the `pbc` are not correctly cleaned-up). If someone is able to make sense of these, he's welcome to speak. 

I'll try again an other day with the various stripped down branches available on @hannesm fork.

**Comment by hannesm** [comment] 2015-05-28 23:12
the (minor) leak seems to be in `read` from Lwt: we use `Lwt_cstruct.read` in `mirage-net-unix` which calls `Lwt_bytes.read`, and somehow from memprof it seems that this does not clear `mutable event_readable : Lwt_engine.event option;` and `hooks_readable : (unit -> unit) Lwt_sequence.t;` from Lwt `file_descr`... any ideas what we're (or lwt?) is doing wrong there?

**Comment by samoht** [comment] 2015-05-28 23:31
An other quick stuff: `Netif.listen` doesn't look very tail-rec ...

**Comment by hannesm** [comment] 2015-05-29 09:24
@samoht nice catch, https://github.com/mirage/mirage-net-unix/pull/16 results in constant memory usage for my nothing branch at least!

**Comment by yomimono** [comment] 2015-05-29 14:22
I'm very late to the party (hi friends!), but mustn't it be the case that we have at least one more leak, since we observed one in unikernels linked against `mirage-net-xen`?

**Comment by samoht** [comment] 2015-05-29 15:26
@hannesm sweet!!

@yomimono indeed. I suspect there might be the same kind of error in the xen backend, but haven't had time to track it down yet.

**Comment by hannesm** [comment] 2015-05-29 17:05
yes, there is some other leak somewhere... I thought the mirage-net-unix fix might lead to rerunning memprof and finding other results (the mirage-seal master still memleaks on unix (unlike the mirage-seal without tls and http)!)

finally got myself a domU with linux, thus I can run memprof myself now (at least in theory) :)

**Comment by hannesm** [comment] 2015-05-30 16:13
ok, some more graphs... unclear how useful they are:
http://memprof.typerex.org/users/9a4bc33e26b77891b75f11aaad96f7f4/2015-05-30_17-37-05_fbc47d66b990cdd2136797ca7099006e_551/index.html includes mirage-net-unix PR 16, and still refers to memory in netif...
http://memprof.typerex.org/users/9a4bc33e26b77891b75f11aaad96f7f4/2015-05-30_17-57-13_9aee504ffccb564e7df118a6a1db0c03_5911/index.html has [mirage-net-unix](https://github.com/hannesm/mirage-net-unix/tree/fixes2) which radically simplifies the listen loop, but nevertheless netif seems to hold onto memory...

I use mirage-seal from my master branch, which includes a compacting GC every 3 seconds...

and the overall problem, running it on xen, is still not touched at all (and not debuggable with ocp-memprof because this relies on binaries and a unix environment)

**Comment by yomimono** [comment] 2015-05-30 17:44
I'm working (slowly) on the Xen side, although not getting much done at the moment.

**Comment by hannesm** [comment] 2015-05-31 14:12
the remaining bytes from my most recent graph, linked above, can be reclaimed by `reset()` all the hashtables in tcp/ip's pcb (or, rephrased: back to square 0, some entries in `channels` are never cleared)

**Comment by hannesm** [comment] 2015-05-31 18:12
running the family of tests on xen, `nothing` is constant, `no-tls` and `no-cohttp` as well. and `master` crashes with out of memory while retaining several connections in `channels` hashtable...
I'd conclude that a) pcb is too big and b) there's some missing transition or c) resource limits for number of tcp connections

**Comment by yomimono** [comment] 2015-06-01 06:58
I've found and poorly-patched one combination of misparsed packet and missing transition that results in pcbs never being cleared when simultaneous closes occur; I'll continue investigating as I suspect this is likely not the only problem.

**Comment by samoht** [comment] 2015-06-01 09:20
The other suspicious bit of code is the `listen` functions of `tcpip_stack_direct` which let the user close the flows given to the callbacks. This could lead to some leak (especially on errors) if the user didn't pay attention too much.

**Comment by hannesm** [comment] 2015-06-01 09:32
@samoht which reminds me that I struggle to understand what the intended semantics / error handling of the stack is. Should `listen`

**Comment by hannesm** [comment] 2015-06-01 09:38
@samoht which reminds me that I struggle to understand the error semantics:
Should `listen` bail if the handler raised an exception? Since a handler is `-> unit io`, there is certainly no intention to report errors back.
The current state of `mirage-net-unix` (and `mirage-net-xen`) do a `ignore_result` wrapped in a `try_lwt` of the handler function. `mirage-net-unix` catches `ENXIO` specifically, and ignores other exceptions (by printing a message and continuing with the listen loop).

My opinion is that no handler should throw any exception. Thus, `listen` should not catch any, but fail hard. If the call to `read` fails, the listen loop should terminate.

**Comment by samoht** [comment] 2015-06-01 09:42
Logging and continuing after an error is ok I think. By default, it is better to not "trust" the callbacks, and an exception which propagate to the listen loop should not kill the whole application.

**Comment by talex5** [comment] 2015-06-01 09:47
Perhaps it should call `async_exception_hook` (either directly or via `Lwt.async`). Then it's up to the application whether to continue or terminate. I'd slightly prefer log-and-continue as the default, but it will depend on the service.

In any case, the current behaviour (silently ignore the error) is clearly wrong.

**Comment by hannesm** [comment] 2015-06-01 10:21
I think this is related to https://github.com/talex5/mirage-www/blob/errors/tmpl/wiki/error-handling.md

I'd really prefer to trust the callbacks. If this is not the case, they should be able to signal error conditions (by having some more elaborate return type than `unit`)!? And who is responsible to clean up potential state of the possible flow when an exception occured (imho only really possible if the callback installs appropriate handlers of which exceptional cases it expects)?

**Comment by samoht** [comment] 2015-06-01 10:49
Well, you never know which exception would be thrown by the callback so we should try to recover as much as possible. Ideally they will not raise anything, and all the ressources will be cleaned up automatically. In the worse case, we can catch the exceptions, print a message. And in any case, we should call `Flow.close` when the callback is done (as we have created the flow before giving it to the callback).

**Comment by samoht** [comment] 2015-06-01 21:20
I confirm that there is still a leak in the `xen` backend. With my shiny `debug` branch and:

```ocaml
let () =
  let open Tcp in
  Log.enable Pcb.debug;
  Log.enable State.debug;
  Stats.Gc.enable ();
  Stats.Gc.full_major true
```

in `static_website/dispatch.ml`  I can still see the memory growing slowly on every request (note: this is without TLS). And the PCB tables are emptied correctly.

**Comment by hannesm** [comment] 2015-06-01 22:59
that sounds great, @samoht \o/

**Comment by yomimono** [comment] 2015-06-02 14:07
@samoht - the debug branch is *really* neat.  

I think I'm seeing different behaviour than you are, or perhaps interpreting the behaviour I'm seeing incorrectly... if I run 1024 `curl`s in sequence against a unikernel generated with `mirage-seal` and a pinned `debug` branch of `tcpip`, here's the last (relevant) bit of log I see on the console:

```
Tcp.State[21|0|1024|0|846k]: Fin_wait_1(452873853)  - Recv_fin -> Closing(452873853)
```

which would seem to imply to me that there are still 1024 channels open.  (This is because there's no mechanism for going from Closing, as we reach in this situation where both sides are attempting to close the connection, to actually closed unless an ACK is received, exacerbated by the fact that the stack ignores RSTs - @balrajsingh and I talked about this off-list, but I can share details more widely if anyone is interested.)  Sending another request after some minutes yields:

```
Tcp.PCB[10|1|1024|0|845k]: process-ack [channels=1024  listens=1 connects=0]
Cannot handle page request order 9!
RX exn Out of memory
Tcp.State[10|0|1024|0|845k]: Syn_rcvd(452856317)  - Recv_ack(452856318) -> Established
```

which certainly seems to suggests to me that we're not properly cleaning everything up?

**Comment by balrajsingh** [comment] 2015-06-02 14:26
Thanks for debugging and testing, my apologies for the bugs and also delay
in getting involved on this thread.  Thanks Mindy for help and discussion
yesterday.

I'm looking at the RST processing right now and I know it's is not fully
implemented (but can be fixed soon). But if there is no RST involved the
expectation should be that all connections will be cleared up. There are
timers that will kick in for this.  Even if the other side disappears the
FIN should be rexmitted a set number of time then go away.

If the other side responds with a RST then we are in the other problem,
which will be fixed soon :).

Even in the case of a simultaneous close it should work fine. If this
doesn't work then it's a new bug. Note that because of the timers and the
time that the GC kicks in it could take up to about a minute for the mem to
be freed. With correct RST processing it should speed up - am working on
writing that up (will post it after my flight lands).

**Comment by samoht** [comment] 2015-06-02 14:35
@yomimono I think this is because of the RST bug that the channels are not cleaned up properly. I was testing with `static_website` only, where the behaviour seems fine. Also in `[10|0|1024|0|845k]` the first 10 means that you still have 10 timer loops going on.

**Comment by samoht** [comment] 2015-06-02 14:40
Thanks @balrajsingh for the detailed explanation, I'm looking forward for the fix :-) Would be nice if we had an automatic way to test we won't regress (we are not very far for having this, don't we @MagnusS or @yomimono?)

@amirmc I am fine with releasing a slightly leaky TLS+mirage integration (as it is a direct issue with TLS) if we say that 1) that's a beta and 2) that we advertise that we have a fix for the leak coming soon. What to do you think?

**Comment by hannesm** [comment] 2015-06-02 14:47
since release is supposed to be next monday, I'd hope to get the fix into tcpip before that.

**Comment by amirmc** [comment] 2015-06-02 14:50
> I am fine with releasing a slightly leaky TLS+mirage integration (as it is a direct issue with TLS) if we say that 1) that's a beta and 2) that we advertise that we have a fix for the leak coming soon. What to do you think?

From the perspective of a *software* release that sounds entirely reasonable to me.  From the perspective of an associated *news/press release* it seems a little weak -- we already have to take care about messaging as it's a new TLS implementation but to further caveat it would diminish the announcement somewhat.

If we can fix the issue 'soon', then I'm perfectly fine with decoupling a release from the *noise* we will make about the release.  i.e. no fanfare/blogs until we've fixed the problem.  Thoughts?

**Comment by amirmc** [comment] 2015-06-03 14:07
Hi folks, pls see my comment in https://github.com/mirage/mirage/issues/409#issuecomment-108438612 regarding the releases.

**Comment by balrajsingh** [comment] 2015-06-03 20:43
So curl, and other browsers as well, close the connection with a FIN
followed by a RST response on all further packets - since we don't process
RST on an Established connection we get these wedged TCPs which manifest as
a mem leak.  Although one (I) can whine that closing a connection with RST
is not good TCP behaviour, since it is allowed, we have to deal with it.
Actually many browsers do this with good justification - that then the
server can then immediately drop the connection and not go through the FIN
timers.

So the only solution is to implement RST processing.  I'm working on it...

The key things that need to be done are:

1. Before accepting an RST packet check if its seq number is valid - it
should ideally be the next seq num, but anything within the window is ok
because preceding packets may have been lost.  I think the ACK number
should also make sense (ie, it should be for one of the seq nums in
flight), but I need to check on this.  The reason to do this is so an
attacker can not easily reset connections by injecting packets - the
attacker will have to get the seq/ack nums right.  If someone can check on
this and find the definitive test it would be most helpful - Vern Paxon has
some papers on this.  This can be done after the release.

2. When a valid RST arrives the state machine should put itself in to a
Reset state and remove the flow from the hash tables - no more packets
should be expected from the other side so this is ok.  Also no more packets
should be sent.  It's like the connection just went kaboom.

3. All frames in the following places should be freed:
    - in the retransmission buffer on the transmit side (in segment.ml)
    - in the out of order queue on the receive side (in segment.ml)
    - in the write buffer (user_buffer.ml)

4. Pcb.read should return saying the connection is in error - it could also
say connection has reached end of stream (like if a fin was received) -
both are ok.  For now maybe just make it as if a fin was received.

5. Pcb.writefn should have the ability to return error - right now it
always return success - if there is no room to write (when other side has
closed window and all write buffer has been used up) it blocks till room
appears - this is the right behaviour and implements needed flow control.
It should now check just before it actually write to the user_buffer
whether the connection is in the Establised or Close_Wait states (the two
states where it is ok to write), if not it should return error.

**Comment by samoht** [comment] 2015-06-10 16:46
The issues mentioned here have been fixed:
- `Netif.listen` which was not tail-recursive on `mirage-net-unix`
- The `RST` packets not properly handled

So I'm closing this. Thanks all for the time spent on investigating and fixing the issue!

**Closed by samoht** 2015-06-10 16:46 UTC
